
name: WakaTime

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:
  # Allows you to run this workflow manually from the Actions tab

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: False
          SHOW_PROFILE_VIEWS : False
          SHOW_LOC_CHART: False
          SHOW_SHORT_INFO : False
          SHOW_DAYS_OF_WEEK : False
          SHOW_COMMIT : False
          SHOW_EDITORS: False
          SHOW_LANGUAGE: False
          SHOW_PROJECTS: False
          SHOW_TIMEZONE: False
          SHOW_LANGUAGE_PER_REPO: False
          SHOW_OS: False
